pipeline:
  name: kf-pipeline
  identifier: kfpipeline
  projectIdentifier: Wipro
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: helm
        identifier: helm
        description: ""
        type: Deployment
        spec:
          deploymentType: NativeHelm
          service:
            serviceRef: macservice
            serviceInputs:
              serviceDefinition:
                type: NativeHelm
                spec:
                  manifests:
                    - manifest:
                        identifier: helm
                        type: HelmChart
                        spec:
                          store:
                            type: Github
                            spec:
                              folderPath: <+input>
          environment:
            environmentRef: macbookk8s
            deployToAll: false
            infrastructureDefinitions:
              - identifier: mac123
          execution:
            steps:
              - step:
                  name: Helm Deployment
                  identifier: helmDeployment
                  type: HelmDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
            rollbackSteps:
              - step:
                  name: Helm Rollback
                  identifier: helmRollback
                  type: HelmRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
